include:
  - project: 'elearning/moodle-ci'
    ref: runners
    file: 'gitlab-ci-base.yml'

## By default, all tests runs, you can uncomment this and remove unwanted tests.
#.job_template: &job_definition
#  script:
#    - EXIT_STATUS=0
#    - moodle-plugin-ci phplint || EXIT_STATUS=$?
#    - moodle-plugin-ci phpcpd || EXIT_STATUS=$?
#    - moodle-plugin-ci phpmd || EXIT_STATUS=$?
#    - moodle-plugin-ci codechecker || EXIT_STATUS=$?
#    - moodle-plugin-ci validate || EXIT_STATUS=$?
#    - moodle-plugin-ci savepoints || EXIT_STATUS=$?
#    - moodle-plugin-ci mustache || EXIT_STATUS=$?
#    - moodle-plugin-ci grunt || EXIT_STATUS=$?
#    - moodle-plugin-ci phpdoc || EXIT_STATUS=$?
#    - moodle-plugin-ci phpunit || EXIT_STATUS=$?
#    - moodle-plugin-ci behat || EXIT_STATUS=$?
#    - exit $EXIT_STATUS

mdl35-70:
  extends: .job_template
  image: moodlehq/moodle-php-apache:7.0-stretch
  tags:
    - docker
  variables:
    MOODLE_BRANCH: "MOODLE_35_STABLE"
